config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  # get "/blog_posts/new", to: "blog_posts#new", as: new_blog_post
  # get "/blog_posts/:id", to: "blog_posts#show", as: blog_post

  # post 
  # put
  # patch
  # delete

  devise_for :users
  # devise_for :users do
  #   delete '/users/sign_out' => 'devise/sessions#destroy'
  # end

  resources :blog_posts
  resources :names

  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    has_rich_text :content
    
    validates :title, presence: true
    validates :content, presence: true

    scope :sorted, -> { order(arel_table[:published_at].desc.nulls_last).order(updated_at: :desc) }
    scope :draft, -> { where(published_at: :nil) }
    scope :published, -> { where("published_at <= ?", Time.current) }
    scope :scheduled, -> { where("published_at > ?", Time.current) }


    def draft?
        published_at.nil? 
    end

    def published?
        published_at? && published_at <= Time.current
    end

    def scheduled?
        published_at? && published_at > Time.current
    end
end

app/models/name.rb
class Name < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_blog_post, except: [:index, :new, :created]

    def index
        @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
    end

    def show
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end

    def new
        @blog_post = BlogPost.new
    end

    def edit
    end

    def update
        if @blog_post.update(blog_post_params)
            redirect_to @blog_post
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def create
        @blog_post = BlogPost.new(blog_post_params)
        if @blog_post.save
            redirect_to @blog_post
        else
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        
        @blog_post.destroy 
        redirect_to root_path
    end

    private
    def set_blog_post
        if user_signed_in?
            @blog_post = BlogPost.find(params[:id])
        else
            @blog_post = BlogPost.published.find(params[:id])
        end
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end

    def blog_post_params
        params.require(:blog_post).permit(:title, :content, :published_at)
    end
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  before_action :set_name, only: %i[ show edit update destroy ]

  # GET /names or /names.json
  def index
    @names = Name.all
  end

  # GET /names/1 or /names/1.json
  def show
  end

  # GET /names/new
  def new
    @name = Name.new
  end

  # GET /names/1/edit
  def edit
  end

  # POST /names or /names.json
  def create
    @name = Name.new(name_params)

    respond_to do |format|
      if @name.save
        format.html { redirect_to name_url(@name), notice: "Name was successfully created." }
        format.json { render :show, status: :created, location: @name }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /names/1 or /names/1.json
  def update
    respond_to do |format|
      if @name.update(name_params)
        format.html { redirect_to name_url(@name), notice: "Name was successfully updated." }
        format.json { render :show, status: :ok, location: @name }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /names/1 or /names/1.json
  def destroy
    @name.destroy

    respond_to do |format|
      format.html { redirect_to names_url, notice: "Name was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_name
      @name = Name.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def name_params
      params.require(:name).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form| %>    
<% if form.object.errors.any? %>
    <div>
        <% form.object.errors.full_messages.each do |message| %>
         <div>
            <%= message %>
        </div>
        <% end %>
    </div>
    <% end %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :content %>
        <%= form.rich_text_area :content %>

    </div>

    <div>
    <%=form.label :published_at %>
    <%= form.datetime_select :published_at %>
    </div>


    <%= form.button %>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Page</h1>
<%= render partial: "form", locals: {blog_post: @blog_post} %>

<%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"} %>

app/views/blog_posts/index.html.erb
<h1>Aloha</h1>
What will you create today!?

  <%
=begin%>
 <div data-controller="clipboard">
  PIN: <input data-clipboard-target="source" type="text" value="1234" readonly>
  <button data-action="clipboard#copy">Copy to Clipboard</button>
  </div>
  <div data-controller="clipboard">
  PIN: <input data-clipboard-target="source" type="text" value="3737" readonly>
  <button data-action="clipboard#copy">Copy to Clipboard</button>
</div> 
<%
=end%>

<div data-controller="clipboard">
  PIN: <input data-clipboard-target="source" type="text" value="3737" readonly>
  <a href="#" data-action="clipboard#copy">Copy to Clipboard</a>
  PIN: <textarea data-clipboard-target="source" readonly>3737</textarea>
</div>


<br />

<%= link_to "Write new blog post!", new_blog_post_path %>

<def index>
<div class="border-8">
    <% @blog_posts.each do |blog_post| %>
    <div>
        <h1><%= link_to blog_post.title, blog_post %></h1>
          <%if blog_post.draft? %>
             <div class="p-2 rounded bg-gray-100 text-gray-900">Draft</div>
          <% elsif blog_post.scheduled? %>
           <div class="p-2 rounded bg-blue-100 text-gray-900">Scheduled</div>
           <% else blog_post.published? %>
             <div class="p-2 rounded bg-green-100 text-gray-900">Published!</div>
       <% end %>
        <%= blog_post.content %>
     <% end %>
    </div>
    </div>
<end>

app/views/blog_posts/new.html.erb
<h1>New blog post</h1>

<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<h1>Blog Show page</h1>

<h1><%= @blog_post.title %></h1>
<p><%= @blog_post.content %>

<div>
<b style="font-size: 40px"><%= link_to "HOME", root_path %></b>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seventest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

       <% if user_signed_in? %>
        <%= link_to "Profile", edit_user_registration_path %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete %>
  
        <% else %>
        <%= link_to "Login", new_user_session_path %>
        <%= link_to "Sign Up", new_user_registration_path %>
       <% end %>

    <%= yield %>
  </body>
</html>

app/views/names/_form.html.erb
<%= form_with(model: name) do |form| %>
  <% if name.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
        <% name.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/names/_name.html.erb
<div id="<%= dom_id name %>">
  <p>
    <strong>Description:</strong>
    <%= name.description %>
  </p>

</div>

app/views/names/edit.html.erb
<h1>Editing name</h1>

<%= render "form", name: @name %>

<br>

<div>
  <%= link_to "Show this name", @name %> |
  <%= link_to "Back to names", names_path %>
</div>

app/views/names/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Names</h1>

<div class="card">
  <div data-controller="hello">
    <input data-hello-target="name" type="text">
    <button data-action="click->hello#greet">Greet</button>
  </div>
  </div>


<div id="names">
  <% @names.each do |name| %>
    <%= render name %>
    <p>
      <%= link_to "Show this name", name %>
    </p>
  <% end %>
</div>

<%= link_to "New name", new_name_path %>

app/views/names/new.html.erb
<h1>New name</h1>

<%= render "form", name: @name %>

<br>

<div>
  <%= link_to "Back to names", names_path %>
</div>

app/views/names/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @name %>

<div>
  <%= link_to "Edit this name", edit_name_path(@name) %> |
  <%= link_to "Back to names", names_path %>

  <%= button_to "Destroy this name", @name, method: :delete %>
</div>